apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: odoo
    service: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
      service: proxy
  template:
    metadata:
      labels:
        app: odoo
        service: proxy
    spec:
      containers:
        - name: odoo-proxy
          image: gcr.io/oscar-test-01/nginx-odoo:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: odoo
    service: proxy
spec:
  type: LoadBalancer
  selector:
    app: odoo
    service: proxy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443

