apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"odoo"},"name":"db","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"odoo"}},"template":{"metadata":{"labels":{"app":"odoo"}},"spec":{"containers":[{"image":"postgres:9.4","name":"db","ports":[{"containerPort":5432}]}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: odoo
  name: db
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: odoo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odoo
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        image: postgres:9.4
        imagePullPolicy: IfNotPresent
        name: db
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"odoo"},"name":"web","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"odoo"}},"template":{"metadata":{"labels":{"app":"odoo"}},"spec":{"containers":[{"image":"odoo:10","name":"web","ports":[{"containerPort":8069}]}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: odoo
  name: web
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: odoo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odoo
    spec:
      containers:
      - image: odoo:9
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 8069
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
